### ISSUE TITLE
專案執行問題

### ISSUE THREAD

**Issue by rina841237** [TheExplainthis/ChatGPT-Line-Bot#53]
按下Run後出現以下訊息
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Line-Bot/main.py", line 19, in <module>
    from src.utils import get_role_and_content
  File "/home/runner/ChatGPT-Line-Bot/src/utils.py", line 1, in <module>
    import opencc
ModuleNotFoundError: No module named 'opencc'

沒有進行到Hello World那一步
請問哪個地方出錯了 謝謝

**Comment by Phoenix-party** [comment]
上面說你沒有安裝opencc的模組 可能要重新執行一下docker

**Comment by mulderyu** [comment]
右下角「shell」那邊，直接打 pip install opencc-python-reimplemented 就可以安裝了，後棉還有很多套件照這方式一個一個安裝就能跑了
