### ISSUE TITLE
求救:按下RUN之後沒有出現Hello World

### ISSUE THREAD

**Issue by jcteacherorg** [TheExplainthis/ChatGPT-Line-Bot#58]
按下RUN之後沒有出現Hello World

出現下面這些
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Line-Bot/main.py", line 2, in <module>
    from flask import Flask, request, abort
  File "/home/runner/ChatGPT-Line-Bot/.pythonlibs/lib/python3.10/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/home/runner/ChatGPT-Line-Bot/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/runner/ChatGPT-Line-Bot/.pythonlibs/lib/python3.10/site-packages/werkzeug/urls.py)

**Comment by Vincentman5690** [comment]
在"requirements.txt"中加入新一行
Werkzeug==2.2.2

**Comment by kaipenguin** [comment]
還是沒有成功

**Comment by kaipenguin** [comment]
按下run出現以下


Traceback (most recent call last):
  File "/home/runner/ChatGPT-Line-Bot-1/main.py", line 2, in <module>
    from flask import Flask, request, abort
  File "/home/runner/ChatGPT-Line-Bot-1/.pythonlibs/lib/python3.10/site-packages/flask/__init__.py", line 5, in <module>
    from .app import Flask as Flask
  File "/home/runner/ChatGPT-Line-Bot-1/.pythonlibs/lib/python3.10/site-packages/flask/app.py", line 30, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/home/runner/ChatGPT-Line-Bot-1/.pythonlibs/lib/python3.10/site-packages/werkzeug/urls.py)

**Comment by only18days** [comment]
> Werkzeug==2.2.2

更新完“requirements.txt"後要記得按下存檔哦，
我試了之後是可以成功出現Hello World的。

**Comment by only18days** [comment]
> 還是沒有成功

更新完“requirements.txt"後要記得按下存檔哦，
我試了之後是可以成功出現Hello World的。

**Comment by neymant** [comment]
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Line-Bot/main.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
 求救出現這種

**Comment by AngChenWu** [comment]
> Traceback (most recent call last): File "/home/runner/ChatGPT-Line-Bot/main.py", line 1, in from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv' 求救出現這種

同求問題解法

**Comment by only18days** [comment]
> Traceback (most recent call last): File "/home/runner/ChatGPT-Line-Bot/main.py", line 1, in from dotenv import load_dotenv ModuleNotFoundError: No module named 'dotenv' 求救出現這種

@neymant  @AngChenWu 有確認過 “requirements.txt" 中有寫到 `python-dotenv==0.21.1` 嗎？
