### ISSUE TITLE
console執行問題

### ISSUE THREAD

**Issue by jim030784** [TheExplainthis/ChatGPT-Line-Bot#6]
想請問為什麼在console端我這邊執行，
為何會出現這樣的錯誤訊息呢?
line在執行後也無法回傳訊息
感謝。
![1](https://user-images.githubusercontent.com/127065185/223007838-53e06a89-73dd-4424-9c0c-754efc81f5a9.png)

**Comment by jim030784** [comment]
![2](https://user-images.githubusercontent.com/127065185/223009118-589f7a53-f067-454a-bedd-88271ff8d138.png)
當我在line傳訊息則會出現這樣的狀況，
感謝回應。

**Comment by TheExplainthis** [comment]
針對圖一，因為 /callback 沒有 GET 的 Method，所以直接打會錯誤唷！
針對圖二，截圖的下半部還有更多的錯誤訊息嗎？

**Comment by maxchen2k** [comment]
172.31.128.1 - - [06/Mar/2023 15:39:51] "POST /callback HTTP/1.1" 200 -
[2023-03-06 15:39:51,911] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "main.py", line 38, in callback
    handler.handle(body, signature)
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/webhook.py", line 259, in handle
    self.__invoke_func(func, event, payload)
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/webhook.py", line 271, in __invoke_func
    func(event)
  File "main.py", line 60, in handle_text_message
    line_bot_api.reply_message(
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/api.py", line 113, in reply_message
    self._post(
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/api.py", line 1860, in _post
    self.__check_error(response)
  File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/api.py", line 1896, in __check_error
    raise LineBotApiError(
linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=3d6769f8-8427-494c-a636-d35d03a81765, error_response={"details": [], "message": "Invalid reply token"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '3d6769f8-8427-494c-a636-d35d03a81765', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Mon, 06 Mar 2023 15:39:51 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 06 Mar 2023 15:39:51 GMT', 'Connection': 'close'}

**Comment by jim030784** [comment]
圖一的部分，我在line develop有加上callback，但有時會出現這樣的訊息耶...
另外附圖
![1](https://user-images.githubusercontent.com/127065185/223291388-cdf38aaf-88dc-4859-a54a-813ae1c73bca.png)

**Comment by TheExplainthis** [comment]
> 172.31.128.1 - - [06/Mar/2023 15:39:51] "POST /callback HTTP/1.1" 200 - [2023-03-06 15:39:51,911] ERROR in app: Exception on /callback [POST] Traceback (most recent call last): File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app response = self.full_dispatch_request() File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request rv = self.dispatch_request() File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args) File "main.py", line 38, in callback handler.handle(body, signature) File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/webhook.py", line 259, in handle self.__invoke_func(func, event, payload) File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/webhook.py", line 271, in __invoke_func func(event) File "main.py", line 60, in handle_text_message line_bot_api.reply_message( File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/api.py", line 113, in reply_message self._post( File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/api.py", line 1860, in _post self.__check_error(response) File "/home/runner/ChatGPT-Line-Bot/venv/lib/python3.10/site-packages/linebot/api.py", line 1896, in __check_error raise LineBotApiError( linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=3d6769f8-8427-494c-a636-d35d03a81765, error_response={"details": [], "message": "Invalid reply token"}, headers={'Content-Type': 'application/json', 'Server': 'envoy', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '3d6769f8-8427-494c-a636-d35d03a81765', 'x-xss-protection': '1; mode=block', 'Content-Length': '33', 'Expires': 'Mon, 06 Mar 2023 15:39:51 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 06 Mar 2023 15:39:51 GMT', 'Connection': 'close'}

可以嘗試看看這個人的解法
https://github.com/line/line-bot-sdk-python/issues/37

**Comment by TheExplainthis** [comment]
> 圖一的部分，我在line develop有加上callback，但有時會出現這樣的訊息耶... 另外附圖 ![1](https://user-images.githubusercontent.com/127065185/223291388-cdf38aaf-88dc-4859-a54a-813ae1c73bca.png)

針對這個問題，可以試著更新 openai 的版本
```
pip install --upgrade openai
```
