### ISSUE TITLE
Run之後，提示：ModuleNotFoundError: No module named 'dotenv'

### ISSUE THREAD

**Issue by brianlien98** [TheExplainthis/ChatGPT-Line-Bot#64]
Run之後，提示：
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Line-Bot-1/main.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

![螢幕擷取畫面 2024-11-12 162112](https://github.com/user-attachments/assets/3f025462-00db-4113-be5a-ea00ae599f6f)

**Comment by moylor123** [comment]
+1
Traceback (most recent call last):
  File "/home/runner/ChatGPT-Line-Bot/main.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
